on: [push, pull_request]
name: build
jobs:
  runhaskell:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: 'latest'
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
